[package]
name = "rust-in-action"
version = "0.1.0"
edition = "2024"

[dependencies]

# [lints]
# workspace = true

# For exploratory dev.
[lints.rust]
unsafe_code = "allow" 
unused = { level = "allow", priority = -1 }

# [lints.clippy]
# unwrap_used = "warn"
# expect_used = "warn"
